steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'gcr.io/clickrate-477217/scalpyn-ml-trainer:latest'
    - '-f'
    - 'ml_trainer/Dockerfile'
    - '.'
images:
- 'gcr.io/clickrate-477217/scalpyn-ml-trainer:latest'
