"""
Tests for profile_create_service.py — create_from_suggestion().

All 20 acceptance criteria are covered. These are unit tests that mock DB
interactions — no real database needed.

Run with:
    pytest backend/tests/test_create_profile_from_suggestion.py -v
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from typing import Any, Optional
from unittest.mock import AsyncMock, MagicMock, patch
import pytest

# ── Service under test ─────────────────────────────────────────────────────────
from app.services.profile_create_service import (
    ProfileCreateService,
    _check_forbidden,
    _build_profile_config,
    _normalize_rule,
    _normalize_signal_condition,
    _normalize_value,
    _stable_rule_id,
    ensure_master_scoring_rules,
    _FORBIDDEN_FIELDS,
)


# ── Fixtures ──────────────────────────────────────────────────────────────────

USER_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000001")
OTHER_USER_ID = uuid.UUID("bbbbbbbb-0000-0000-0000-000000000002")
SUGG_ID = uuid.UUID("cccccccc-0000-0000-0000-000000000003")
COMBO_ID = uuid.UUID("dddddddd-0000-0000-0000-000000000004")
PROFILE_ID = uuid.UUID("eeeeeeee-0000-0000-0000-000000000005")


def _make_suggestion(
    status="pending_user_approval",
    confidence_level="HIGH",
    confidence_score=75.0,
    source_combination_id=None,
    created_profile_id=None,
    run_id=None,
    signals=None,
    scoring=None,
    block_rules=None,
    master_rules=None,
    config=None,
) -> MagicMock:
    s = MagicMock()
    s.id = SUGG_ID
    s.user_id = USER_ID
    s.run_id = run_id or uuid.uuid4()
    s.source_combination_id = source_combination_id
    s.source_type = "counterfactual_dynamic"
    s.source_run_id = s.run_id
    s.profile_id = PROFILE_ID
    s.profile_name = "Source Profile"
    s.validation_status = "validated"
    s.actionability_status = "validated"
    s.diff_json = {"before": None, "after": {"profile": "shadow"}}
    s.rollback_payload = {"action": "archive_generated_profile"}
    s.status = status
    s.confidence_level = confidence_level
    s.confidence_score = confidence_score
    s.created_profile_id = created_profile_id
    s.suggested_profile_name = "PI Test Profile"
    s.suggested_profile_description = "Generated by PI Engine"
    s.suggested_profile_family = "MOMENTUM"
    s.suggested_signals_json = signals or {
        "logic": "AND",
        "conditions": [
            {"field": "rsi", "operator": "<", "value": 45},
        ],
    }
    s.suggested_scoring_json = scoring or {
        "weights": {"liquidity": 25, "momentum": 25, "market_structure": 25, "signal": 25},
    }
    s.suggested_block_rules_json = block_rules or [
        {"field": "rsi", "operator": ">", "value": 78},
    ]
    s.required_master_scoring_rules_json = master_rules or [
        {"indicator": "rsi", "operator": "<", "value": 45, "points": 15, "category": "momentum"},
    ]
    s.suggested_config_json = config or {}
    s.quantitative_explanation = None
    s.ai_explanation = None
    s.risk_notes = None
    return s


def _make_combo(overfit_risk=False) -> MagicMock:
    c = MagicMock()
    c.id = COMBO_ID
    c.user_id = USER_ID
    c.overfit_risk = overfit_risk
    return c


def _make_db(suggestion=None, combo=None, no_suggestion=False) -> AsyncMock:
    """Build a mock AsyncSession that returns appropriate objects."""
    db = AsyncMock()

    # Track flushed/added objects
    db._added = []
    db.add = lambda obj: db._added.append(obj)
    db.flush = AsyncMock()
    db.commit = AsyncMock()

    async def _execute(q, *args, **kwargs):
        result = MagicMock()

        # Detect which model is being queried by inspecting the query string
        q_str = str(q)
        if "ProfileSuggestion" in q_str or "profile_suggestions" in q_str.lower():
            scalar_result = None if no_suggestion else (suggestion or _make_suggestion())
            result.scalars.return_value.first.return_value = scalar_result
        elif "ProfileRuleCombination" in q_str or "profile_rule_combinations" in q_str.lower():
            result.scalars.return_value.first.return_value = combo
        elif "ConfigProfile" in q_str or "config_profiles" in q_str.lower():
            # Return None to trigger creation of master score config
            result.scalars.return_value.first.return_value = None
        else:
            result.scalars.return_value.first.return_value = None

        return result

    db.execute = _execute
    return db


# ── Helper to patch Profile model ─────────────────────────────────────────────

class _FakeProfile:
    def __init__(self, **kwargs):
        self.id = PROFILE_ID
        for k, v in kwargs.items():
            setattr(self, k, v)


# ── Tests ─────────────────────────────────────────────────────────────────────

class TestNormalization:
    """Unit tests for pure normalization helpers."""

    def test_normalize_value_comma_decimal(self):
        assert _normalize_value("3,14") == 3.14

    def test_normalize_value_float_passthrough(self):
        assert _normalize_value(42.5) == 42.5

    def test_normalize_value_int_passthrough(self):
        assert _normalize_value(10) == 10

    def test_normalize_rule_renames_field_to_indicator(self):
        r = _normalize_rule({"field": "rsi", "operator": "gt", "value": "45,5"})
        assert r["indicator"] == "rsi"
        assert "field" not in r
        assert r["operator"] == ">"
        assert r["value"] == 45.5

    def test_normalize_rule_keeps_indicator(self):
        r = _normalize_rule({"indicator": "adx", "operator": ">=", "value": 25})
        assert r["indicator"] == "adx"

    def test_normalize_signal_condition_uses_field_contract(self):
        r = _normalize_signal_condition(
            {"indicator": "volume_spike", "operator": ">=", "value": 1.2}
        )
        assert r["field"] == "volume_spike"
        assert "indicator" not in r

    def test_build_profile_config_preserves_distinct_signal_indicators(self):
        suggestion = _make_suggestion(signals={
            "logic": "AND",
            "conditions": [
                {"field": "rsi", "operator": ">=", "value": 72},
                {"field": "volume_spike", "operator": ">=", "value": 1.2},
                {"field": "orderbook_depth_usdt", "operator": ">=", "value": 20000},
            ],
        })

        config = _build_profile_config(suggestion, [], [], "SHADOW_ONLY")

        assert [c["field"] for c in config["signals"]["conditions"]] == [
            "rsi",
            "volume_spike",
            "orderbook_depth_usdt",
        ]
        assert config["entry_triggers"]["conditions"] == config["signals"]["conditions"]

    def test_check_forbidden_detects_outcome(self):
        conds = [{"field": "outcome", "operator": "=", "value": "TP_HIT"}]
        assert "outcome" in _check_forbidden(conds)

    def test_check_forbidden_detects_pnl_pct(self):
        conds = [{"indicator": "pnl_pct", "operator": ">", "value": 0.01}]
        assert "pnl_pct" in _check_forbidden(conds)

    def test_check_forbidden_allows_rsi(self):
        conds = [{"indicator": "rsi", "operator": "<", "value": 45}]
        assert _check_forbidden(conds) == []

    def test_stable_rule_id_deterministic(self):
        id1 = _stable_rule_id("rsi", "<", 45, "momentum")
        id2 = _stable_rule_id("rsi", "<", 45, "momentum")
        assert id1 == id2

    def test_stable_rule_id_prefix(self):
        rid = _stable_rule_id("rsi", "<", 45, "momentum")
        assert rid.startswith("sr_")


class TestCreateProfileService:
    """Integration-style tests for ProfileCreateService using mocked DB."""

    @pytest.mark.asyncio
    async def test_01_creates_profile_from_valid_suggestion(self):
        """Criteria 1, 3-11, 13-14."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID
            )

        assert result["status"] == "created"
        assert "profile_id" in result
        assert result["is_shadow_only"] is True          # criteria 10
        assert result["live_trading_enabled"] is False   # criteria 11

    @pytest.mark.asyncio
    async def test_02_dry_run_does_not_commit(self):
        """Criteria 2 — dry_run returns preview without writes."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID, dry_run=True
            )

        assert result["status"] == "dry_run"
        assert "profile_payload" in result
        db.commit.assert_not_called()
        # No profile add should have happened
        assert not any(isinstance(o, _FakeProfile) for o in db._added)

    @pytest.mark.asyncio
    async def test_03_other_user_gets_lookup_error(self):
        """Criteria 3 — multi-tenancy: other user's suggestion → LookupError."""
        svc = ProfileCreateService()
        db = _make_db(no_suggestion=True)

        with pytest.raises(LookupError, match="não encontrada"):
            await svc.create_from_suggestion(
                db=db, user_id=OTHER_USER_ID, suggestion_id=SUGG_ID
            )

    @pytest.mark.asyncio
    async def test_04_low_confidence_blocked_without_confirm(self):
        """Criteria 4 — LOW confidence blocks without flag."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion(confidence_level="LOW", confidence_score=10.0)
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.ConfigProfile", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID,
                confirm_low_confidence=False,
            )

        assert result["status"] == "blocked"
        assert any("LOW confidence" in r for r in result["blocked_reasons"])

    @pytest.mark.asyncio
    async def test_04b_low_confidence_allowed_with_confirm(self):
        """LOW confidence passes with confirm_low_confidence=True."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion(confidence_level="LOW", confidence_score=10.0)
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID,
                confirm_low_confidence=True,
            )

        assert result["status"] == "created"

    @pytest.mark.asyncio
    async def test_05_overfit_risk_blocked_without_confirm(self):
        """Criteria 5 — overfit_risk blocks without flag."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion(source_combination_id=COMBO_ID)
        combo = _make_combo(overfit_risk=True)
        db = _make_db(suggestion=suggestion, combo=combo)

        with patch("app.services.profile_create_service.ConfigProfile", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID,
                confirm_overfit_risk=False,
            )

        assert result["status"] == "blocked"
        assert any("overfitting" in r.lower() for r in result["blocked_reasons"])

    @pytest.mark.asyncio
    async def test_06_already_created_returns_existing(self):
        """Criteria 6 — idempotency: status=created returns existing profile."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion(status="created", created_profile_id=PROFILE_ID)
        db = _make_db(suggestion=suggestion)

        result = await svc.create_from_suggestion(
            db=db, user_id=USER_ID, suggestion_id=SUGG_ID
        )

        assert result["status"] == "already_created"
        assert result["profile_id"] == str(PROFILE_ID)
        db.commit.assert_not_called()

    @pytest.mark.asyncio
    async def test_07_existing_master_rule_reused(self):
        """Criteria 7 — reuse_existing_master_rules: existing rule is NOT duplicated."""
        existing_rule = {
            "id": "sr_rsi_12345678",
            "indicator": "rsi",
            "operator": "<",
            "value": 45.0,
            "points": 15,
            "category": "momentum",
            "enabled": True,
        }
        db = AsyncMock()
        db._added = []
        db.add = lambda o: db._added.append(o)
        db.flush = AsyncMock()
        db.commit = AsyncMock()

        # Mock config_profile with existing rule
        cp_mock = MagicMock()
        cp_mock.config_json = json.dumps({
            "thresholds": {"strong_buy": 80},
            "rules": [existing_rule],
        })
        cp_mock.id = uuid.uuid4()
        cp_mock.updated_at = datetime.now(timezone.utc)

        async def _execute(q, *a, **kw):
            res = MagicMock()
            res.scalars.return_value.first.return_value = cp_mock
            return res

        db.execute = _execute

        with patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await ensure_master_scoring_rules(
                db=db,
                user_id=USER_ID,
                required_rules=[{"indicator": "rsi", "operator": "<", "value": 45, "points": 15, "category": "momentum"}],
                create_missing=True,
                dry_run=False,
            )

        assert len(result["reused"]) == 1
        assert len(result["created"]) == 0
        assert result["reused"][0]["id"] == "sr_rsi_12345678"

    @pytest.mark.asyncio
    async def test_08_missing_master_rule_created(self):
        """Criteria 8 — create_missing_master_rules=True creates new rule."""
        db = AsyncMock()
        db._added = []
        db.add = lambda o: db._added.append(o)
        db.flush = AsyncMock()
        db.commit = AsyncMock()

        # Empty config
        cp_mock = MagicMock()
        cp_mock.config_json = json.dumps({"rules": []})
        cp_mock.id = uuid.uuid4()
        cp_mock.updated_at = datetime.now(timezone.utc)

        async def _execute(q, *a, **kw):
            res = MagicMock()
            res.scalars.return_value.first.return_value = cp_mock
            return res

        db.execute = _execute

        with patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await ensure_master_scoring_rules(
                db=db,
                user_id=USER_ID,
                required_rules=[{"indicator": "adx", "operator": ">=", "value": 25, "points": 10, "category": "trend"}],
                create_missing=True,
                dry_run=False,
            )

        assert len(result["created"]) == 1
        assert result["created"][0]["indicator"] == "adx"

    def test_09_no_master_rule_duplication(self):
        """Criteria 9 — stable ID is deterministic; calling twice yields same ID."""
        id1 = _stable_rule_id("adx", ">=", 25, "trend")
        id2 = _stable_rule_id("adx", ">=", 25, "trend")
        assert id1 == id2

    @pytest.mark.asyncio
    async def test_10_profile_has_is_shadow_only_true(self):
        """Criteria 10 — is_shadow_only must be True in result."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID
            )

        assert result["is_shadow_only"] is True

    @pytest.mark.asyncio
    async def test_11_profile_has_live_trading_false(self):
        """Criteria 11 — live_trading_enabled must be False."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            result = await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID
            )

        assert result["live_trading_enabled"] is False

    @pytest.mark.asyncio
    async def test_12_generated_by_set(self):
        """Criteria 12 — generated_by='profile_intelligence'."""
        captured_kwargs = {}

        class _CaptureProfile:
            def __init__(self, **kwargs):
                self.id = PROFILE_ID
                captured_kwargs.update(kwargs)
                for k, v in kwargs.items():
                    setattr(self, k, v)

        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _CaptureProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        assert captured_kwargs.get("generated_by") == "profile_intelligence"

    @pytest.mark.asyncio
    async def test_13_generated_from_suggestion_id_set(self):
        """Criteria 13 — generated_from_suggestion_id must be set."""
        captured_kwargs = {}

        class _CaptureProfile:
            def __init__(self, **kwargs):
                self.id = PROFILE_ID
                captured_kwargs.update(kwargs)
                for k, v in kwargs.items():
                    setattr(self, k, v)

        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _CaptureProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        assert str(captured_kwargs.get("generated_from_suggestion_id")) == str(SUGG_ID)

    @pytest.mark.asyncio
    async def test_14_config_has_signals_scoring_block_rules(self):
        """Criteria 14 — config contains signals, entry_triggers, scoring, block_rules."""
        captured_kwargs = {}

        class _CaptureProfile:
            def __init__(self, **kwargs):
                self.id = PROFILE_ID
                captured_kwargs.update(kwargs)
                for k, v in kwargs.items():
                    setattr(self, k, v)

        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _CaptureProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        cfg = captured_kwargs.get("config", {})
        assert "signals" in cfg, "signals missing from config"
        assert "entry_triggers" in cfg, "entry_triggers missing from config"
        assert "scoring" in cfg, "scoring missing from config"
        assert "block_rules" in cfg, "block_rules missing from config"

    @pytest.mark.asyncio
    async def test_15_suggestion_status_becomes_applied(self):
        """Suggestion lifecycle uses the governed applied status."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        assert suggestion.status == "applied"

    @pytest.mark.asyncio
    async def test_16_suggestion_created_profile_id_set(self):
        """Criteria 16 — suggestion.created_profile_id populated."""
        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        assert suggestion.created_profile_id is not None

    @pytest.mark.asyncio
    async def test_17_pi_audit_log_registered(self):
        """Criteria 17 — ProfileIntelligenceAuditLog created with correct event_type."""
        pi_audit_instances = []

        class _CapturePIAudit:
            def __init__(self, **kwargs):
                self.id = uuid.uuid4()
                pi_audit_instances.append(kwargs)
                for k, v in kwargs.items():
                    setattr(self, k, v)

        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", _CapturePIAudit), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        assert len(pi_audit_instances) >= 1
        assert pi_audit_instances[0]["event_type"] == "CREATE_PROFILE_FROM_SUGGESTION"

    @pytest.mark.asyncio
    async def test_18_profile_audit_log_registered(self):
        """Criteria 18 — ProfileAuditLog created with change_source=profile_intelligence."""
        pal_instances = []

        class _CapturePAL:
            def __init__(self, **kwargs):
                pal_instances.append(kwargs)
                for k, v in kwargs.items():
                    setattr(self, k, v)

        svc = ProfileCreateService()
        suggestion = _make_suggestion()
        db = _make_db(suggestion=suggestion)

        with patch("app.services.profile_create_service.Profile", _FakeProfile), \
             patch("app.services.profile_create_service.ProfileAuditLog", _CapturePAL), \
             patch("app.services.profile_create_service.ProfileIntelligenceAuditLog", MagicMock), \
             patch("app.services.profile_create_service.ConfigProfile", MagicMock), \
             patch("app.services.profile_create_service.ConfigAuditLog", MagicMock):
            await svc.create_from_suggestion(db=db, user_id=USER_ID, suggestion_id=SUGG_ID)

        assert len(pal_instances) >= 1
        assert pal_instances[0].get("change_source") == "profile_intelligence"
        assert pal_instances[0].get("previous_config") is None

    @pytest.mark.asyncio
    async def test_19_invalid_mode_raises(self):
        """No live trading — ACTIVE mode raises ValueError before DB access."""
        svc = ProfileCreateService()
        db = AsyncMock()

        with pytest.raises(ValueError, match="Live trading permanece desativado"):
            await svc.create_from_suggestion(
                db=db, user_id=USER_ID, suggestion_id=SUGG_ID, mode="ACTIVE"
            )

    def test_20_forbidden_fields_comprehensive(self):
        """Criteria 20 — all forbidden post-entry fields are in the guard set."""
        required = {
            "outcome", "pnl_pct", "exit_price", "future_outcome", "future_pnl_pct",
            "holding_seconds", "mae_pct", "mfe_pct",
        }
        missing = required - _FORBIDDEN_FIELDS
        assert not missing, f"Forbidden fields missing from guard: {missing}"
