"""Phase 3 shadow validation cycle.

1. Add validated_at, win_rate_before, win_rate_after, validation_reason to
   profile_adjustment_versions (needed by run_shadow_validation_cycle).
2. Tombstone all existing PENDING_VALIDATION PAVs (1,812+ corrupt records:
   current_value=null + uniform diff 65→70 + Phase 3 never implemented).
3. Cancel stuck APAs (PROCESSING → CANCELLED).
4. Mark orphaned PAS as SUPERSEDED (SHADOW_APPLIED → SUPERSEDED).

Revision ID: 121_shadow_validation_cycle
Revises: 120_mutation_audit_enrichment
Create Date: 2026-06-28
"""
from __future__ import annotations

from alembic import op
from sqlalchemy import text

revision = "121_shadow_validation_cycle"
down_revision = "120_mutation_audit_enrichment"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Add Phase 3 result columns (single ALTER TABLE statement)
    op.execute(text("""
        ALTER TABLE profile_adjustment_versions
            ADD COLUMN IF NOT EXISTS validated_at     TIMESTAMPTZ NULL,
            ADD COLUMN IF NOT EXISTS win_rate_before  NUMERIC(6,4) NULL,
            ADD COLUMN IF NOT EXISTS win_rate_after   NUMERIC(6,4) NULL,
            ADD COLUMN IF NOT EXISTS validation_reason TEXT NULL
    """))

    # Step 2: Tombstone all PENDING_VALIDATION PAVs generated by the buggy cycle
    op.execute(text("""
        UPDATE profile_adjustment_versions
        SET shadow_validation_status = 'INVALIDATED',
            rollback_available       = false,
            validation_reason        = 'tombstoned_2026-06-28: '
                                       'current_value=null AND uniform_diff_65_70 '
                                       'AND phase3_not_implemented'
        WHERE shadow_validation_status = 'PENDING_VALIDATION'
    """))

    # Step 3: Cancel stuck APAs that were PROCESSING for the now-invalidated suggestions
    op.execute(text("""
        UPDATE autopilot_pending_actions
        SET action_status = 'CANCELLED',
            updated_at    = now()
        WHERE action_status = 'PROCESSING'
          AND suggestion_id IN (
              SELECT id FROM profile_adjustment_suggestions
              WHERE status = 'SHADOW_APPLIED'
          )
    """))

    # Step 4: Supersede PAS whose PAVs are now INVALIDATED
    op.execute(text("""
        UPDATE profile_adjustment_suggestions
        SET status     = 'SUPERSEDED',
            updated_at = now()
        WHERE status = 'SHADOW_APPLIED'
          AND id IN (
              SELECT suggestion_id
              FROM profile_adjustment_versions
              WHERE shadow_validation_status = 'INVALIDATED'
          )
    """))


def downgrade() -> None:
    # Restoring tombstoned records would re-introduce corrupt data — not supported.
    raise NotImplementedError(
        "Downgrade not supported: would re-introduce 1,812+ corrupt PENDING_VALIDATION records"
    )
